### ISSUE TITLE
App crashed on Heroku

### ISSUE THREAD

**Issue by Hazelstar** [Hazelstar/Home_Chef#68]
App crashed on Heroku when the booker user clicks on one of the chatrooms in "my messages" section in their profile.

_#<Thread:0x0000559eee6c3d78@/app/vendor/bundle/ruby/2.6.0/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):_

**Comment by Hazelstar** [comment]
Fixed with REDISCLOUD:30 added on Heroku.

Should be closed only when tested in prod and working

**Comment by mariongayon** [comment]
Fixed
